### ISSUE TITLE
Apply post handlers for embedded associations

### ISSUE THREAD

**Issue by smogili1** [JKHeadley/rest-hapi#197]
Hi - 

I have defined some pre and post handlers for the user model. And another model (modelA) is associated with the user model. However the pre and post handlers I defined in the user model are not applied when I query modelA with $embed = user. Is there a way to apply the post handler for user model even when it is retrieved as an embedded association.

Thanks,

**Comment by JKHeadley** [comment]
Hi @smogili1, there is no built-in option for doing this, since an `$embed` is basically a shortcut for calling [mongoose populate](https://github.com/JKHeadley/rest-hapi/blob/b3117a29a7ab763b5890099fa05bc3a8e4e8c2c8/utilities/query-helper.js#L380), which is not a rest-hapi method.

That being said, you have several options that might help you accomplish what you are trying to do. The easiest option is to take advantage of the `GET /modelA/{ownerId}/user` endpoint, which will get all of modelA's associated users and apply the middleware (pre/post handlers) to each user.

Another option would be to write a `post` middleware for `modelA` that would grab all the embedded users' `_id`s and replace the user documents with the results of a [list](https://resthapi.com/docs/mongoose-wrapper-methods.html#list) call using a [where query](https://resthapi.com/docs/querying.html) with an array of their `_id`s.

You could also potentially solve this with a [policy](https://resthapi.com/docs/policies.html) if you need to repeat the functionality across many models.
