### ISSUE TITLE
How can associate with multiple model?

### ISSUE THREAD

**Issue by samseralam** [JKHeadley/rest-hapi#39]
Hi, @JKHeadley 
I need to make association with multiple field, so is there any way to define association with more than one model?. 
example:
my schema is like this:
 masterField: [{

             abc: [{
                 facility: {
                     type: Types.ObjectId,
                     ref: "abc"
                 }
             }],
             xyz: [{
                 item: {
                     type: Types.ObjectId,
                     ref: "xyz"
                 }
         }]

}]

associations: {
type:.............?
model:...........?

}

How can i associate abc and xyz model with masterField so that i can embed masterField to populate abc and xyz ?

**Comment by JKHeadley** [comment]
I don't believe what you are trying to do will work with the regular `$embed` query.  However you might be able to accomplish this with a solution similar to the one posted in #31.  

If this turns out to be too much trouble, it would probably be easier to split up/add more models (and associate them) rather than trying to encapsulate all the relationships into one field.

**Comment by samseralam** [comment]
Thanks @JKHeadley 
Absolutely! split up/add more models +1
