### ISSUE TITLE
PUT on many to many updates existing rather than creating new

### ISSUE THREAD

**Issue by delateurj** [JKHeadley/rest-hapi#88]
Hi...I am finding this library very useful...found what is either an issue or misunderstanding on my part.
If I use the example and create a group document and then create a permission document and then use the PUT /group/{ownerId}/permission/{childId} to create a group_permission document, this works and a document is created in the group_permission collection.   However, if I attempt to create another one with the same group and permission document ids (and do not include the _id of the existing group_permission document in the body), rather than getting another group_permission document it updates the existing one.   While for groups and permissions this is probably okay, in general in a many to many (including some of my use cases), I think one should be able to create multiple link documents for the same two related documents.  For example, parts and cars have a many to many relationship...for the same part and same car there would be a car_part document for every instance of the part in the car.
Thanks,
Joe.

**Comment by JKHeadley** [comment]
Hi @delateurj, glad you are getting some use out of it!

Yes you have observed correctly. I agree it would be useful to be able to manage multiple link documents for two related documents using the generated endpoints. However this would certainly require more endpoints than what are currently generated, and I simply have not had enough time to give some serious thought on how to best implement that feature. 

In my own projects I've found that when this need arises it is often the case that I'm better off creating a new model that takes the place of the linking model. This approach gives more control and flexibility and makes it easier to handle the (usually) more complex requirements of the linking model in question.

Using your car_part example, you could create a new model and name it something like `carPartDetail` (rather than the standard `car_part` linking model form).  You can then use one-many/many-one relationships to fill in the many-many relationship:

`car.model.js`
```javascript
//...
associations: {
        carPartDetails: {
          type: "ONE_MANY",
          alias: "car-part-detail",
          foreignField: "car",
          model: "carPartDetail"
        }
}
//...
```

`part.model.js`
```javascript
//...
associations: {
        carPartDetails: {
          type: "ONE_MANY",
          alias: "car-part-detail",
          foreignField: "part",
          model: "carPartDetail"
        }
}
//...
```

`carPartDetail.model.js`
```javascript
'use strict';

module.exports = function (mongoose) {
  var modelName = "carPartDetail";
  var Types = mongoose.Schema.Types;
  var Schema = new mongoose.Schema({
    car: {
      type: Types.ObjectId,
      ref: "car",
      allowOnUpdate: false,
      required: true
    },
    part: {
      type: Types.ObjectId,
      ref: "part",
      allowOnUpdate: false,
      required: true
    },
    details: {
      type: Types.String
    },
  }, { collection: modelName });
    
  Schema.statics = {
    collectionName:modelName,
    routeOptions: {
      associations: {
        car: {
          type: "MANY_ONE",
          model: "car",
        },
        part: {
          type: "MANY_ONE",
          model: "part",
        }
      }
    }
  };

  return Schema;
};
```

Hopefully this helps. I would love to hear any ideas you have about improving this. Thanks!

**Comment by delateurj** [comment]
Thanks for the quick response and your suggestion.  I'll let you know if I come up with any other ideas. 
Regards,
Joe.
